services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: company-rag-postgres
    environment:
      POSTGRES_DB: companyrag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: yigitsancar/company-rag-backend:latest
    container_name: company-rag-backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    image: yigitsancar/company-rag-frontend:latest
    container_name: company-rag-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    container_name: company-rag-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: company-rag-grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
volumes:
  postgres_data:
  grafana_data:
